# Generated by Django 5.2.7 on 2025-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_en",
            field=models.SlugField(max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_uk",
            field=models.SlugField(max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uk",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
