# Generated by Django 5.2.7 on 2025-10-22 16:05

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_content_en_post_content_uk_post_slug_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_en",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_uk",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published at"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=320, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug_en",
            field=models.SlugField(
                max_length=320, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug_uk",
            field=models.SlugField(
                max_length=320, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=300, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_uk",
            field=models.CharField(max_length=300, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"], name="blog_post_status_5b2843_idx"
            ),
        ),
    ]
