# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content_alter_post_content_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/featured/",
                verbose_name="Featured image",
            ),
        ),
    ]
