# Generated by Django 5.2.7 on 2025-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_featured_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_status_5b2843_idx",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug_en",
            field=models.SlugField(
                blank=True,
                max_length=320,
                null=True,
                unique=True,
                verbose_name="Slug (English)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug_uk",
            field=models.SlugField(
                blank=True,
                max_length=320,
                null=True,
                unique=True,
                verbose_name="Slug (Ukrainian)",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["published_at"], name="blog_post_publish_698bc0_idx"
            ),
        ),
    ]
