# Generated by Django 5.2.7 on 2025-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_blog_post_status_5b2843_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=160, null=True, verbose_name="Name"),
                ),
                (
                    "name_uk",
                    models.CharField(max_length=160, null=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="Slug"),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        max_length=180, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "slug_uk",
                    models.SlugField(
                        max_length=180, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["slug"], name="blog_catego_slug_fc0bb9_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="blog.category",
                verbose_name="Categories",
            ),
        ),
    ]
